// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeViewExample.Persistence;

namespace TreeViewExample.Migrations
{
    [DbContext(typeof(OrgUnitDbContext))]
    [Migration("20211128215418_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TreeViewExample.Models.OrgUnitBase", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgUnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentUnitId")
                        .HasColumnType("int");

                    b.HasKey("UnitId");

                    b.HasIndex("ParentUnitId");

                    b.ToTable("OrgUnits");

                    b.HasDiscriminator<string>("OrgUnitType").HasValue("OrgUnitBase");
                });

            modelBuilder.Entity("TreeViewExample.Models.OrgUnitType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrgUnitTypes");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "cmp",
                            Name = "Company"
                        },
                        new
                        {
                            Id = "2",
                            Code = "sub",
                            Name = "SubUnit"
                        },
                        new
                        {
                            Id = "3",
                            Code = "ret",
                            Name = "RetailStore"
                        });
                });

            modelBuilder.Entity("TreeViewExample.Models.Company", b =>
                {
                    b.HasBaseType("TreeViewExample.Models.OrgUnitBase");

                    b.HasDiscriminator().HasValue("Company");
                });

            modelBuilder.Entity("TreeViewExample.Models.RetStore", b =>
                {
                    b.HasBaseType("TreeViewExample.Models.OrgUnitBase");

                    b.HasDiscriminator().HasValue("RetStore");
                });

            modelBuilder.Entity("TreeViewExample.Models.SubUnit", b =>
                {
                    b.HasBaseType("TreeViewExample.Models.OrgUnitBase");

                    b.HasDiscriminator().HasValue("SubUnit");
                });

            modelBuilder.Entity("TreeViewExample.Models.OrgUnitBase", b =>
                {
                    b.HasOne("TreeViewExample.Models.OrgUnitBase", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentUnitId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TreeViewExample.Models.OrgUnitBase", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
